server:
  port: 8181
  tomcat:
    max-swallow-size: 100MB
    max-http-post-size: 100MB

logging:
  level:
    org:
      springframework:
        web: trace
      apache: trace

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 3000000

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres?charSet=UTF-8'
    username: postgres
    password: 7890123456Upet
  jpa:
    show-sql: true
    #    defer-datasource-initialization: true - убрали настройку потому что отключили Hibernate и создаем и наполняем таблицы сами
    hibernate:
      ddl-auto: update
  aop:
    proxy-target-class: true
    auto: true

service:
  clients:
    file-storage-client:
      url: 'http://localhost:8282/rest/fileStorage'