server:
  port: 8181

spring:
  resources:
    cache:
      cache control:
        cache-private: false
        max-age: 3600
  datasource:
#    url: 'jdbc:postgresql://localhost:5432/example'
#    username: user
#    password: password
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: 7890123456Upet
  thymeleaf:
    cache: false
    mode: HTML
    enabled: true
    debug: true
  jpa:
    show-sql: true
    #    defer-datasource-initialization: true - убрали настройку потому что отключили Hibernate и создаем и наполняем таблицы сами
    hibernate:
      ddl-auto: update
  security:
    enabled: false
service:
  clients:
    file-storage-client:
      url: 'http://localhost:8282/rest/fileStorage'
