server:
  port: 8181

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/'
    username: postgres
    password: 7890123456Upet

  jpa:
    show-sql: true


service:
  clients:
    file-storage-client:
      url: 'http://localhost:8282'